//Ride ranking weights
#ifndef KCDECISIONWEIGHTS_H
#define KCDECISIONWEIGHTS_H

#define QUEUE_LENGTH_MODIFIER 0.25
#define PRICE_WEIGHT 1.0
#define FREE_PRICE 0.001


#define QUEUED_SATISFACTION_PENALTY 0.5

#endif
